# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  database: gubei
from:
  adapter: mysql2
  pool: 5
  reconnect: true
  username: root
  password: root
  host: 127.0.0.1
  database: gubei_test